const APIData =[
    {
        key: '1',
        imageUrl: 'https://imgs.search.brave.com/mA6MSMMHoxE3l9J5VJAmb3ihy2bEYTulZlWjjQvXl5g/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9jZG4u/cGl4YWJheS5jb20v/cGhvdG8vMjAxNy8w/NC8xMC8yMi8yOC9y/ZXNpZGVuY2UtMjIx/OTk3Ml82NDAuanBn',
        title: '1 Kanal House for sale',
        address: 'DHA Phase 6, Lahore',
        beds: 5,
        bath: 6,
        coveredAreaSQFT: '2350 sqft',
        propertyType: 'house',
        isCommercial: 'Yes',
        price: 65000000
      },
      {
        key: '2',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '3',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '4',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '5',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '6',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '7',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '8',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '9',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '10',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '11',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '12',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '13',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '14',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '15',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '16',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '17',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '18',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '19',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '20',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '21',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '22',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '23',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '24',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '25',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '26',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '27',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '28',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '29',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      },
      {
        key: '30',
        imageUrl: 'https://imgs.search.brave.com/WhIQcWFfSnd2GUC-0FezYuzk2VIMNDhjl2F383qkqo8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudW5zcGxhc2gu/Y29tL3Bob3RvLTE1/NTgwMzYxMTctMTVk/ODJhOTBiOWIxP2l4/bGliPXJiLTQuMC4z/Jml4aWQ9TTN3eE1q/QTNmREI4TUh4elpX/RnlZMmg4TVRoOGZI/SmxZV3dsTWpCbGMz/UmhkR1Y4Wlc1OE1I/eDhNSHg4ZkRBPSZ3/PTEwMDAmcT04MA.jpeg',
        title: '2 Kanal Office for sale',
        address: 'Bahria Town, Islamabad',
        beds: 8,
        bath: 10,
        coveredAreaSQFT: '4000 sqft',
        propertyType: 'office',
        isCommercial: 'No',
        price: 80000000
      }
]



export default APIData